version: "3"

services:

  api:
    build: .
    command: node ./build/index.js
    container_name: node-api
    links:
      - mongo
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - influxdb
      - grafana
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB_MAIN: f_meter_db
      WAIT_HOSTS: mongo:27017

  mongo:
     image: mongo:3.5.7
     restart: always
     volumes:
      - ./data:/data/db
     ports: 
      - "27017:27017"
  
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true

      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      
  grafana:
    depends_on:
      - influxdb
    image: grafana/grafana
    ports:
      - "3000:3000"
